- src/components/styled-multi-select-2.tsx
- yarn.lock
This should close issue 4 in the tracker for you.  I went with pl-2 to try to keep it consistent with the other paddings I saw.
> Added padding to items in multi-select-2 dropdown.

- .eslintrc.json
- README.md
- src/components/character-aggregation-display.tsx
- src/components/styled-select-2.tsx
- src/pages/poe/atlas.tsx
- src/pages/poe/characters.tsx
Added `"root": true` to the eslint config so it stops throwing the same warning every time.
Added  `--frozen-lockfile` flag to the readme instructions.
Cleaned up imports in `character-aggregation-display.tsx`.
Removed `key` from `Row` in `character-aggregation-display.tsx`, `Row` is not iterated over so it doesn't need a `key` value.
Changed cursor to `cursor-pointer` in `styled-select-2.tsx` clickable elements.
Removed unnecessary fragment elements in `atlas.tsx`  and `characters.tsx`.
Added a `key` to the iterated over `tr` in `atlas.tsx`.
> Some small changes to nagging issues.

- src/components/create-bulk-listing-modal.tsx
Fix on Bug-report "Seethrough export item data on black background" submitted by Jay
> fix - bulk export bg + opacity

- src/components/atlas-passives-tree/ap-tree-connection.tsx
- src/components/atlas-passives-tree/ap-tree-node.tsx
- src/components/atlas-passives-tree/atlas-passives-tree.tsx
- src/components/character-stats-display.tsx
- src/components/loading-indicator.tsx
- src/pages/poe/character/[characterId].tsx
- src/pages/poe/characters/[userId].tsx
A big one here.  The characters per user page updated to have real info and the atlas passives tree.
Both atlas passive trees reworked.  Profiling shows render time cut almost in half.  Tooltips added per node.
Trees can now be rendered anywhere with just `<AtlasPassivesTree version={"3.20"} />` and `<SkillTree version={"3.20"}/>`.
Both optionally take `selectedNodes` which is just an Array<number>.  Internally they take care of optimizations.
> Character page issues

- src/components/landingpage.tsx
- src/components/styled-footer.tsx
While testing out the landing page on my phone today noticed a few padding/height issues. Resolved those by setting up height to screen and a few other changes to the VH on the images.
Will definitely need to add in a lightbox feature for the images to help users see more clearly on phone.
> Quick Style Fixes

- src/components/currency-value-display.tsx
- src/components/hsparkline.tsx
- src/components/sortable-table-header.tsx
- src/components/styled-nav-bar.tsx
- src/pages/poe/economy/[league].tsx
Updated some alignments on the economy page for mobile and desktop.
Mobile makes the history graph hidden but keeps the %{color text}.
> Economy Page 

- src/components/styled-multi-select-multi-filter.tsx
- src/pages/_app.tsx
- src/pages/tft/bulk-tool.tsx
also added a method to sort arrays by many keys
> minor improvements to modal select component

- package.json
- src/contexts/options-context.tsx
- src/pages/_app.tsx
- added usehooks-ts with cool useLocalStorage hook which works with next 
- created options context which allows creating easy to manage useOptions hooks for each key stored in options in localStorage
- wrapped whole app with PoeStackOptionsProvider
- could improve sanitization of localStorage objects, right now it just check whether all keys exist
> options context

- src/components/item-mouseover.tsx
- src/pages/poe/character/[characterId].tsx
- src/styles/globals.css
- tailwind.config.js
- yarn.lock
Updated gem and equipment tooltip textboxes to display color based on item rarity & item type.
Created some nice new dividers between item/gem text.
> Equipment & Gem tooltip Update

- src/components/landingpage.tsx
- src/components/styled-multi-select-2.tsx
- src/components/theme-changer.tsx
- src/components/trees/atlas-passives-tree.tsx
- src/components/trees/nodes-tree/nodes-tree.tsx
- src/components/trees/nodes-tree/tree-connection.tsx
- src/styles/globals.css
- tailwind.config.js
- Skill Tree color change
- Landing Page Carousel UI tweaked + fixed double click issues
> Small Updates

- package.json
- src/pages/poe/faq.tsx
- yarn.lock
FAQ Youtube Embed
- Added 1 Click TFT bulk sale with redirect
- Added Character Ladder Page
Displays videos side by side on large screens and scales down to single videos for mobile.
> FAQ Tutorials Added

- src/components/ggg-auth-btn.tsx
- src/components/styled-dropdown.tsx
- src/components/styled-nav-bar.tsx
- src/components/styled-select-2.tsx
- src/pages/_app.tsx
- src/pages/ggg/connected.tsx
There still some issues on the dropdown and the select that will need a fix on another PR
**Before:**
**After:**
> Aligning items on the navbar

- src/components/item-mouseover.tsx
Without dat fix i cant see gem description on hover
https://imgur.com/0u43Cac
> Fix for hover for gem in character page

- .github/workflows/prettier.yml
- .prettierrc
- .vscode/settings.json
- package.json
- yarn.lock
I've opened this pull request to set up Prettier and add a GitHub action to check future pull requests. Here's what I've done:
- Created a new Prettier configuration file based on the code style of the project
- Added a prettier plugin to sort imports consistently
- Added a new GitHub action that runs Prettier on all future pull requests
By setting up Prettier, we can ensure that all code contributions to the project are formatted consistently, which will improve code quality and readability. The new GitHub action will help us catch any formatting issues early on, making it easier for other developers to review and merge pull requests.
> Prettier Setup

- public/assets/common/peakpx.jpg:Zone.Identifier
- src/components/stash-view/stash-view-search-card.tsx
- src/pages/poe/stash-view.tsx
Collapsable control cards, expand/hide for league & stash tab and expand/hide for the min quant, value and total value.
> Stashview control cards collapsible

- src/components/library/styled-button.tsx
- src/components/stash-view/stash-view-item-table.tsx
> [PS] Add new page controls

- src/components/library/styled-dropdown.tsx
- src/components/nav/notification-button.tsx
- src/components/stash-view/exporters/stash-view-generic-tft-exporter-card.tsx
- src/components/stash-view/stash-view-tab-selection-card.tsx
- src/pages/pricing.tsx
- Changes some dropdown styling to make it look more modern, fixes positioning. (Profile dropdown + Post to TFT button)
- Solves issue in which clicking a tab name in the bulk tool does not tick the box.
- Changes notification component to work correctly, especially on click out.
- Debounces pricing search as it was a major performance bottleneck. (Typing too fast would make the site lag, render way too many things on an already complex page, and even some keystrokes were lost).
> Minor QoL and style updates

- src/components/stash-view/stash-view-layout.tsx
> add a collapse icon for the stash graph

- src/components/ggg-auth-btn.tsx
- src/components/nav/styled-nav-top.tsx
> put discord info and connect button at top, make it more clear which info is which

- src/pages/poe-stack/sage-development.tsx
https://www.loom.com/share/4c60ce5dc9754b20b3440cc49510a2bc?sid=fb4d009c-ee35-435e-b29a-ae2bbeedd574
Goes with https://github.com/PoeStack/poestack-sage/pull/26 to enable one click auth for poestack-sage
> Add sage dev page
